Feat/unique numbers request and confirm
pitro-patro/unitto-backend pull request #1
Opened 2022-01-26 00:51 UTC by teller2016

New features
- unique number generator
- unique number request API
- unique number confirm API

2022-02-03 12:59 UTC, hywook4 requested changes
테스트용 코드는 전부 삭제해주세요 :)

2022-02-03 12:59 UTC, hywook4 commented on src/main/resources/static/home.html
> +</html>
안쓰는거 이제 지웁시다.

2022-02-03 12:59 UTC, hywook4 commented on src/main/java/com/pitropatro/unitto/service/RedisService.java
> +}
Redis repository랑 하는 역할이 다른게 없어보이는데 왜 있는지 모르겠습니다. 
지우는걸 추천

2022-02-03 13:00 UTC, hywook4 commented on src/main/java/com/pitropatro/unitto/controller/MainController.java
> +}
[7838468](https://github.com/pitro-patro/unitto-backend/pull/1/commits/78384689fc644e2a6e0d9e08728d072d11d079c4)

2022-02-04 13:48 UTC, teller2016 reviewed
불필요 테스트 파일 삭제 완료

2022-02-04 13:53 UTC, teller2016 commented on src/main/java/com/pitropatro/unitto/service/RedisService.java
> +}
[5eb491a](https://github.com/pitro-patro/unitto-backend/pull/1/commits/5eb491a67dd9a0a7349a822bb5fd5157a6c4848d)
삭제 완료

2022-02-04 13:53 UTC, teller2016 commented on src/main/resources/static/home.html
> +</html>
[5eb491a](https://github.com/pitro-patro/unitto-backend/pull/1/commits/5eb491a67dd9a0a7349a822bb5fd5157a6c4848d)
삭제 완료

2022-02-04 13:53 UTC, teller2016 commented on src/main/java/com/pitropatro/unitto/controller/MainController.java
> +}
[5eb491a](https://github.com/pitro-patro/unitto-backend/pull/1/commits/5eb491a67dd9a0a7349a822bb5fd5157a6c4848d)
삭제 완료

2022-02-06 14:40 UTC, hywook4 requested changes

2022-02-06 14:40 UTC, hywook4 commented on src/main/java/com/pitropatro/unitto/service/LotteryService.java
> +        String existingLotteryNumber = redisRepository.getValueByKey(lotteryNumberInString);
Naming이 조금 그렇네요.... 왜냐면 로또 번호를 key로 하고 value 는 confirm여부 즉 true/false인데

2022-02-06 14:40 UTC, hywook4 commented on src/main/java/com/pitropatro/unitto/service/LotteryService.java
> +        String existingLotteryNumber = redisRepository.getValueByKey(lotteryNumberInString);
Boolean 으로 바꾸십쇼

2022-02-06 14:40 UTC, hywook4 commented on src/main/java/com/pitropatro/unitto/service/LotteryService.java
> +        if(existingLotteryNumber == null || existingLotteryNumber == "true"){
java에서 문자열 비교는 .equal())? 인가 isEqual()이런걸로 해야합니다.

2022-02-07 09:39 UTC, teller2016 commented on src/main/resources/static/home.html
> +</html>
[3f3a5b4](https://github.com/pitro-patro/unitto-backend/pull/1/commits/3f3a5b465c958d7a502e44260e8b4441426d07a1)
삭제 완료

2022-02-07 09:39 UTC, teller2016 commented on src/main/java/com/pitropatro/unitto/service/LotteryService.java
> +        String existingLotteryNumber = redisRepository.getValueByKey(lotteryNumberInString);
[3f3a5b4](https://github.com/pitro-patro/unitto-backend/pull/1/commits/3f3a5b465c958d7a502e44260e8b4441426d07a1)
Naming + Boolean으로 변경하여 처리함

2022-02-07 09:40 UTC, teller2016 commented on src/main/java/com/pitropatro/unitto/service/LotteryService.java
> +        if(existingLotteryNumber == null || existingLotteryNumber == "true"){
[3f3a5b4](https://github.com/pitro-patro/unitto-backend/pull/1/commits/3f3a5b465c958d7a502e44260e8b4441426d07a1)
Boolean으로 타입 변경하여 처리함

2022-02-07 09:42 UTC, teller2016 commented
[3f3a5b4](https://github.com/pitro-patro/unitto-backend/pull/1/commits/3f3a5b465c958d7a502e44260e8b4441426d07a1)
- Exception 처리 추가함
- 불필요 파일 제거

2022-02-08 09:30 UTC, merged